In [1]:
from rfo_core.aws.iam import get_aws_session
from rfo_core.configuration import (aws_key, aws_secret, aws_region_default)
import awswrangler as wr
import boto3 as bt

In [2]:
def aws_get_session(region: str = aws_region_default) -> bt.Session:
    return get_aws_session(aws_key=aws_key, aws_secret=aws_secret, aws_region=region)
session = aws_get_session(region='us-east-1')

In [3]:
table="rfo_weather_enriched"

In [4]:
# checking all unique regions in the table
sql = "SELECT DISTINCT region FROM rfo_weather_enriched"
unique_datatypes = wr.athena.read_sql_query(
    sql=sql,
    database="rfo_analytics",
    boto3_session=session
)
print(unique_datatypes['region'].tolist())

KeyboardInterrupt:

In [4]:
# checking all unique datatypes in the table
sql = "SELECT DISTINCT datatype FROM rfo_weather_enriched"
unique_datatypes = wr.athena.read_sql_query(
    sql=sql,
    database="rfo_analytics",
    boto3_session=session
)
unique_datatypes['datatype'].tolist()

['temperature_avg',
 'cloudCover',
 'temperature_max',
 'windChill',
 'electric_cdd',
 'population_hdd',
 'windDirection',
 'weighted_hdd',
 'gas_hdd',
 'relativeHumidity',
 'temperature_min',
 'gas_cdd',
 'weighted_cdd',
 'temperature',
 'electric_hdd',
 'heatIndex',
 'dewpoint',
 'windSpeed',
 'population_cdd']

In [26]:
# Query to get entries with a specific date
sql = "SELECT station_name, avgvalue, CAST(datetime AS DATE) AS date FROM rfo_weather_enriched WHERE datatype = 'gas_cdd' AND avgvalue IS NOT NULL AND CAST(datetime AS DATE) = DATE '2021-09-01'"
random_entries = wr.athena.read_sql_query(
    sql=sql,
    database="rfo_analytics",
    boto3_session=session
)
print(random_entries)

     station_name  avgvalue        date
0             JFK       0.0  2021-09-01
1    Central Park       0.0  2021-09-01
2      Charleston       0.0  2021-09-01
3       Vancouver       0.0  2021-09-01
4     Parkersburg       0.0  2021-09-01
..            ...       ...         ...
255  Williamsport       0.0  2021-09-01
256    Burlington       0.0  2021-09-01
257        Dayton       0.0  2021-09-01
258        Peoria       0.0  2021-09-01
259   Houston IAH       0.0  2021-09-01

[260 rows x 3 columns]

In [29]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(random_entries.sort_values('avgvalue', ascending=False))

          station_name  avgvalue        date
75                <NA>       6.9  2021-09-01
158              CONUS       6.9  2021-09-01
242       CONSUM. EAST       3.1  2021-09-01
231          PRODUCING       2.4  2021-09-01
7        SOUTH CENTRAL       2.3  2021-09-01
173               EAST       1.8  2021-09-01
45        CONSUM. WEST       1.5  2021-09-01
113            MIDWEST       1.3  2021-09-01
105            PACIFIC       0.9  2021-09-01
89            MOUNTAIN       0.6  2021-09-01
243            Medford       0.0  2021-09-01
2           Charleston       0.0  2021-09-01
229          Milwaukee       0.0  2021-09-01
230          San Diego       0.0  2021-09-01
232           Columbia       0.0  2021-09-01
233          Rochester       0.0  2021-09-01
234          Jonesboro       0.0  2021-09-01
235             Toledo       0.0  2021-09-01
236          Flagstaff       0.0  2021-09-01
237           Stockton       0.0  2021-09-01
238          Lexington       0.0  2021-09-01
239           Hamilton       0.0  2021-09-01
240               Reno       0.0  2021-09-01
241      Atlantic City       0.0  2021-09-01
259        Houston IAH       0.0  2021-09-01
20            Winnipeg       0.0  2021-09-01
21             Ardmore       0.0  2021-09-01
22          KanCty Inl       0.0  2021-09-01
23                 PJM       0.0  2021-09-01
24              Lufkin       0.0  2021-09-01
25             Burbank       0.0  2021-09-01
26          La Guardia       0.0  2021-09-01
27               Huron       0.0  2021-09-01
28             Toronto       0.0  2021-09-01
29         Brownsville       0.0  2021-09-01
30              Boston       0.0  2021-09-01
31          St. Joseph       0.0  2021-09-01
32           Nashville       0.0  2021-09-01
33          Binghamton       0.0  2021-09-01
34           Covington       0.0  2021-09-01
35             Seattle       0.0  2021-09-01
36         Baton Rouge       0.0  2021-09-01
37          Dodge City       0.0  2021-09-01
38              Denton       0.0  2021-09-01
39        Grand Rapids       0.0  2021-09-01
40             Madison       0.0  2021-09-01
41          Des Moines       0.0  2021-09-01
42             Atlanta       0.0  2021-09-01
43              Duncan       0.0  2021-09-01
44           Melbourne       0.0  2021-09-01
46            Bismarck       0.0  2021-09-01
47          Eau Claire       0.0  2021-09-01
48               Paris       0.0  2021-09-01
49             Orlando       0.0  2021-09-01
50        Grand Junctn       0.0  2021-09-01
51               Utica       0.0  2021-09-01
52        White Plains       0.0  2021-09-01
53            Carlsbad       0.0  2021-09-01
54            Edmonton       0.0  2021-09-01
55    Interntnl. Falls       0.0  2021-09-01
56          Farmington       0.0  2021-09-01
57               Minot       0.0  2021-09-01
58            Billings       0.0  2021-09-01
59        North Platte       0.0  2021-09-01
60              Joplin       0.0  2021-09-01
61       Wichita Falls       0.0  2021-09-01
62      Corpus Christi       0.0  2021-09-01
63   Dallas Fort Worth       0.0  2021-09-01
64            Montreal       0.0  2021-09-01
65        Wash. Dulles       0.0  2021-09-01
66            Portland       0.0  2021-09-01
67      Los Ang Dwntwn       0.0  2021-09-01
68             Roanoke       0.0  2021-09-01
69            Syracuse       0.0  2021-09-01
70               Islip       0.0  2021-09-01
71                AESO       0.0  2021-09-01
72               Omaha       0.0  2021-09-01
73                NWPP       0.0  2021-09-01
74               Miami       0.0  2021-09-01
76               ERCOT       0.0  2021-09-01
77         Plattsburgh       0.0  2021-09-01
78             Norfolk       0.0  2021-09-01
79      Ft. Lauderdale       0.0  2021-09-01
80         Albuquerque       0.0  2021-09-01
81       Chicago Midwy       0.0  2021-09-01
82            Columbia       0.0  2021-09-01
83           Green Bay       0.0  2021-09-01
84             Midland       0.0  2021-09-01
85                Wink       0.0  2021-09-01
86         Thunder Bay       0.0  2021-09-01
87           Knoxville       0.0  2021-09-01
88           El Dorado       0.0  2021-09-01
90         Fort Nelson       0.0  2021-09-01
91            Rockford       0.0  2021-09-01
92               Tyler       0.0  2021-09-01
93             Concord       0.0  2021-09-01
94           St. Louis       0.0  2021-09-01
95           Riverside       0.0  2021-09-01
96             Detroit       0.0  2021-09-01
97             Augusta       0.0  2021-09-01
98           Ft. Myers       0.0  2021-09-01
99          Pittsburgh       0.0  2021-09-01
100         Sacramento       0.0  2021-09-01
101    College Station       0.0  2021-09-01
102         Charleston       0.0  2021-09-01
103            Decatur       0.0  2021-09-01
104         Bridgeport       0.0  2021-09-01
106      Pincher Creek       0.0  2021-09-01
107              NYISO       0.0  2021-09-01
108          SOUTHWEST       0.0  2021-09-01
109       Lake Charles       0.0  2021-09-01
110            Buffalo       0.0  2021-09-01
111           Junction       0.0  2021-09-01
112            Stanley       0.0  2021-09-01
114             Austin       0.0  2021-09-01
115             Tacoma       0.0  2021-09-01
116              Dover       0.0  2021-09-01
117           Victoria       0.0  2021-09-01
118             Mobile       0.0  2021-09-01
119         Washington       0.0  2021-09-01
120        San Antonio       0.0  2021-09-01
121      New Braunfels       0.0  2021-09-01
122              NEISO       0.0  2021-09-01
123              Ocala       0.0  2021-09-01
124           Richmond       0.0  2021-09-01
125            El Paso       0.0  2021-09-01
126      Grand Prairie       0.0  2021-09-01
127         Evansville       0.0  2021-09-01
128         Providence       0.0  2021-09-01
129            Lubbock       0.0  2021-09-01
130            Cotulla       0.0  2021-09-01
131     Salt Lake City       0.0  2021-09-01
132            Ontario       0.0  2021-09-01
133           Red Deer       0.0  2021-09-01
134         Huntington       0.0  2021-09-01
135            Sudbury       0.0  2021-09-01
136        Tallahassee       0.0  2021-09-01
137          SOUTHEAST       0.0  2021-09-01
138             Albany       0.0  2021-09-01
139           Cheyenne       0.0  2021-09-01
140         Alexandria       0.0  2021-09-01
141             Duluth       0.0  2021-09-01
142            Oakland       0.0  2021-09-01
143      Fort St. John       0.0  2021-09-01
144           Hartford       0.0  2021-09-01
145      Mineral Wells       0.0  2021-09-01
146           San Jose       0.0  2021-09-01
147          Worcester       0.0  2021-09-01
148           Ok. City       0.0  2021-09-01
149               Erie       0.0  2021-09-01
150         MISO NORTH       0.0  2021-09-01
151         Laredo AFB       0.0  2021-09-01
152        Bakersfield       0.0  2021-09-01
153              Tulsa       0.0  2021-09-01
154          Yuma MCAS       0.0  2021-09-01
155          Las Vegas       0.0  2021-09-01
156           Beeville       0.0  2021-09-01
157        Minneapolis       0.0  2021-09-01
228                SPP       0.0  2021-09-01
159          Westfield       0.0  2021-09-01
160           Glendive       0.0  2021-09-01
161          Pendleton       0.0  2021-09-01
162         Morgantown       0.0  2021-09-01
163             Lander       0.0  2021-09-01
164        Los Angeles       0.0  2021-09-01
165        Little Rock       0.0  2021-09-01
166             Fresno       0.0  2021-09-01
167          McAlester       0.0  2021-09-01
168        Springfield       0.0  2021-09-01
169         Manchester       0.0  2021-09-01
170         Camp Mabry       0.0  2021-09-01
171      San Francisco       0.0  2021-09-01
172             Newark       0.0  2021-09-01
19         Springfield       0.0  2021-09-01
174      Klamath Falls       0.0  2021-09-01
175         Fort Wayne       0.0  2021-09-01
176            Lansing       0.0  2021-09-01
177           Amarillo       0.0  2021-09-01
178               MISO       0.0  2021-09-01
179         Wilmington       0.0  2021-09-01
180            Decatur       0.0  2021-09-01
181         MISO SOUTH       0.0  2021-09-01
182            Phoenix       0.0  2021-09-01
183            Massena       0.0  2021-09-01
184             Yakima       0.0  2021-09-01
185       Watford City       0.0  2021-09-01
186              Fargo       0.0  2021-09-01
187            Calgary       0.0  2021-09-01
188             London       0.0  2021-09-01
189        Quebec City       0.0  2021-09-01
190       Indianapolis       0.0  2021-09-01
191          New Haven       0.0  2021-09-01
192    West Palm Beach       0.0  2021-09-01
193     Cape Girardeau       0.0  2021-09-01
194          Baltimore       0.0  2021-09-01
195         San Angelo       0.0  2021-09-01
196               IESO       0.0  2021-09-01
197         Birmingham       0.0  2021-09-01
198               Alva       0.0  2021-09-01
199      Fort McMurray       0.0  2021-09-01
200          Galveston       0.0  2021-09-01
201          Allentown       0.0  2021-09-01
202           Portland       0.0  2021-09-01
203         Shreveport       0.0  2021-09-01
204        New Orleans       0.0  2021-09-01
205      Chicago OHare       0.0  2021-09-01
206       Akron-Canton       0.0  2021-09-01
207            Wichita       0.0  2021-09-01
208     St. Petersburg       0.0  2021-09-01
209            Jackson       0.0  2021-09-01
210          Cleveland       0.0  2021-09-01
211             Topeka       0.0  2021-09-01
212             Tucson       0.0  2021-09-01
213       Jacksonville       0.0  2021-09-01
214             Denver       0.0  2021-09-01
215       Philadelphia       0.0  2021-09-01
216           Beaumont       0.0  2021-09-01
217        Great Falls       0.0  2021-09-01
218          Red Bluff       0.0  2021-09-01
219        Sioux Falls       0.0  2021-09-01
220            Spokane       0.0  2021-09-01
221        Hattiesburg       0.0  2021-09-01
222     Wallops Island       0.0  2021-09-01
223             Sidney       0.0  2021-09-01
224      Daytona Beach       0.0  2021-09-01
225              CAISO       0.0  2021-09-01
226              Boise       0.0  2021-09-01
227         Louisville       0.0  2021-09-01
4          Parkersburg       0.0  2021-09-01
245             Blythe       0.0  2021-09-01
246              Tampa       0.0  2021-09-01
247           Columbus       0.0  2021-09-01
248       Poughkeepsie       0.0  2021-09-01
249      SaultSteMarie       0.0  2021-09-01
250            Memphis       0.0  2021-09-01
251         Harrisburg       0.0  2021-09-01
252               Gage       0.0  2021-09-01
253            Abilene       0.0  2021-09-01
254             Conroe       0.0  2021-09-01
255       Williamsport       0.0  2021-09-01
256         Burlington       0.0  2021-09-01
257             Dayton       0.0  2021-09-01
258             Peoria       0.0  2021-09-01
1         Central Park       0.0  2021-09-01
0                  JFK       0.0  2021-09-01
5               Ottawa       0.0  2021-09-01
6          New Bedford       0.0  2021-09-01
244         Ral-Durham       0.0  2021-09-01
8             Monahans       0.0  2021-09-01
9           Cincinnati       0.0  2021-09-01
10          Rapid City       0.0  2021-09-01
11                Waco       0.0  2021-09-01
12             Glasgow       0.0  2021-09-01
13           Charlotte       0.0  2021-09-01
14           Williston       0.0  2021-09-01
15          Hagerstown       0.0  2021-09-01
16           Kalamazoo       0.0  2021-09-01
17              Eugene       0.0  2021-09-01
18            Scranton       0.0  2021-09-01
3            Vancouver       0.0  2021-09-01

In [34]:
# Query to get entries with a specific date
sql = "SELECT station_name, avgvalue, CAST(datetime AS DATE) AS date FROM rfo_weather_enriched WHERE datatype = 'population_cdd' AND avgvalue IS NOT NULL AND CAST(datetime AS DATE) = DATE '2021-09-01'"
random_entries = wr.athena.read_sql_query(
    sql=sql,
    database="rfo_analytics",
    boto3_session=session
)
print(random_entries)

     station_name  avgvalue        date
0    Williamsport       0.0  2021-09-01
1            MISO       0.0  2021-09-01
2         Buffalo       0.0  2021-09-01
3         Sudbury       0.0  2021-09-01
4       St. Louis       0.0  2021-09-01
..            ...       ...         ...
255      Syracuse       0.0  2021-09-01
256       Decatur       0.0  2021-09-01
257   New Orleans       0.0  2021-09-01
258      Scranton       0.0  2021-09-01
259          AESO       0.0  2021-09-01

[260 rows x 3 columns]

In [35]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(random_entries.sort_values('avgvalue', ascending=False))

          station_name  avgvalue        date
183              CONUS       8.6  2021-09-01
52                <NA>       8.6  2021-09-01
127       CONSUM. EAST       4.1  2021-09-01
28           PRODUCING       3.1  2021-09-01
50       SOUTH CENTRAL       3.1  2021-09-01
21                EAST       3.0  2021-09-01
244       CONSUM. WEST       1.3  2021-09-01
76             MIDWEST       1.1  2021-09-01
80             PACIFIC       0.8  2021-09-01
237           MOUNTAIN       0.6  2021-09-01
228            Roanoke       0.0  2021-09-01
19          Wilmington       0.0  2021-09-01
242         Des Moines       0.0  2021-09-01
241         Charleston       0.0  2021-09-01
239               Reno       0.0  2021-09-01
240        Thunder Bay       0.0  2021-09-01
238        Springfield       0.0  2021-09-01
236           Edmonton       0.0  2021-09-01
1                 MISO       0.0  2021-09-01
3              Sudbury       0.0  2021-09-01
233          Riverside       0.0  2021-09-01
232             London       0.0  2021-09-01
247         Providence       0.0  2021-09-01
246      Fort St. John       0.0  2021-09-01
245            Stanley       0.0  2021-09-01
0         Williamsport       0.0  2021-09-01
259               AESO       0.0  2021-09-01
18              Sidney       0.0  2021-09-01
17               Minot       0.0  2021-09-01
16            Ok. City       0.0  2021-09-01
15             Calgary       0.0  2021-09-01
14               NYISO       0.0  2021-09-01
13         Los Angeles       0.0  2021-09-01
12          Manchester       0.0  2021-09-01
235              Huron       0.0  2021-09-01
234      Wichita Falls       0.0  2021-09-01
9             Portland       0.0  2021-09-01
8           Sacramento       0.0  2021-09-01
23      St. Petersburg       0.0  2021-09-01
22           SOUTHWEST       0.0  2021-09-01
20          La Guardia       0.0  2021-09-01
51           Green Bay       0.0  2021-09-01
49         Plattsburgh       0.0  2021-09-01
48       Daytona Beach       0.0  2021-09-01
47          Camp Mabry       0.0  2021-09-01
46              Tacoma       0.0  2021-09-01
45           New Haven       0.0  2021-09-01
44           Charlotte       0.0  2021-09-01
43          MISO SOUTH       0.0  2021-09-01
42             Detroit       0.0  2021-09-01
41        Central Park       0.0  2021-09-01
40          Pittsburgh       0.0  2021-09-01
39              Newark       0.0  2021-09-01
38            Stockton       0.0  2021-09-01
37          Cincinnati       0.0  2021-09-01
36         Sioux Falls       0.0  2021-09-01
67           Williston       0.0  2021-09-01
66             Lubbock       0.0  2021-09-01
65            Winnipeg       0.0  2021-09-01
64        Indianapolis       0.0  2021-09-01
63             Spokane       0.0  2021-09-01
62           Galveston       0.0  2021-09-01
61              Lufkin       0.0  2021-09-01
60          Eau Claire       0.0  2021-09-01
59          Harrisburg       0.0  2021-09-01
58                IESO       0.0  2021-09-01
11        Grand Junctn       0.0  2021-09-01
10              Boston       0.0  2021-09-01
56        Wash. Dulles       0.0  2021-09-01
57         Houston IAH       0.0  2021-09-01
53           Flagstaff       0.0  2021-09-01
55              Peoria       0.0  2021-09-01
83          Shreveport       0.0  2021-09-01
82      Salt Lake City       0.0  2021-09-01
81         Great Falls       0.0  2021-09-01
54   Dallas Fort Worth       0.0  2021-09-01
79         Little Rock       0.0  2021-09-01
78           Knoxville       0.0  2021-09-01
77                 SPP       0.0  2021-09-01
75           Melbourne       0.0  2021-09-01
74         San Antonio       0.0  2021-09-01
73           McAlester       0.0  2021-09-01
72        Watford City       0.0  2021-09-01
71              Dayton       0.0  2021-09-01
70            Cheyenne       0.0  2021-09-01
69       Fort McMurray       0.0  2021-09-01
68         Parkersburg       0.0  2021-09-01
99               Paris       0.0  2021-09-01
98               Miami       0.0  2021-09-01
97             Ontario       0.0  2021-09-01
96            Portland       0.0  2021-09-01
95              Denver       0.0  2021-09-01
94          Evansville       0.0  2021-09-01
93             Atlanta       0.0  2021-09-01
92          KanCty Inl       0.0  2021-09-01
91            Hamilton       0.0  2021-09-01
90           Baltimore       0.0  2021-09-01
89          Washington       0.0  2021-09-01
88         Bakersfield       0.0  2021-09-01
87            Hartford       0.0  2021-09-01
86            Billings       0.0  2021-09-01
85             Massena       0.0  2021-09-01
84             Memphis       0.0  2021-09-01
115              Islip       0.0  2021-09-01
114              Utica       0.0  2021-09-01
113               NWPP       0.0  2021-09-01
112           Beeville       0.0  2021-09-01
111      Mineral Wells       0.0  2021-09-01
110            Toronto       0.0  2021-09-01
109          Nashville       0.0  2021-09-01
108       Lake Charles       0.0  2021-09-01
107              Ocala       0.0  2021-09-01
106         Rapid City       0.0  2021-09-01
105             Yakima       0.0  2021-09-01
104             Lander       0.0  2021-09-01
103       Grand Rapids       0.0  2021-09-01
102          Ft. Myers       0.0  2021-09-01
101     Cape Girardeau       0.0  2021-09-01
100          Yuma MCAS       0.0  2021-09-01
131             Toledo       0.0  2021-09-01
130         Fort Wayne       0.0  2021-09-01
129        Hattiesburg       0.0  2021-09-01
128           Glendive       0.0  2021-09-01
126        Albuquerque       0.0  2021-09-01
125              Fargo       0.0  2021-09-01
124              Dover       0.0  2021-09-01
123      San Francisco       0.0  2021-09-01
122           Columbia       0.0  2021-09-01
121                PJM       0.0  2021-09-01
120         St. Joseph       0.0  2021-09-01
119        New Bedford       0.0  2021-09-01
118           San Jose       0.0  2021-09-01
117              NEISO       0.0  2021-09-01
116            Concord       0.0  2021-09-01
147      New Braunfels       0.0  2021-09-01
146       White Plains       0.0  2021-09-01
145          Red Bluff       0.0  2021-09-01
144             Mobile       0.0  2021-09-01
143      Pincher Creek       0.0  2021-09-01
142           Red Deer       0.0  2021-09-01
141      SaultSteMarie       0.0  2021-09-01
140           Columbia       0.0  2021-09-01
139           Junction       0.0  2021-09-01
138          El Dorado       0.0  2021-09-01
137      Chicago OHare       0.0  2021-09-01
136          Westfield       0.0  2021-09-01
135            Orlando       0.0  2021-09-01
134            Glasgow       0.0  2021-09-01
133              Omaha       0.0  2021-09-01
132     Corpus Christi       0.0  2021-09-01
163        Fort Nelson       0.0  2021-09-01
162         Charleston       0.0  2021-09-01
161         Binghamton       0.0  2021-09-01
160             Ottawa       0.0  2021-09-01
159             Denton       0.0  2021-09-01
158        Quebec City       0.0  2021-09-01
157           Victoria       0.0  2021-09-01
156            Decatur       0.0  2021-09-01
155             Blythe       0.0  2021-09-01
154       Philadelphia       0.0  2021-09-01
153         Louisville       0.0  2021-09-01
152          Las Vegas       0.0  2021-09-01
151         Dodge City       0.0  2021-09-01
150            El Paso       0.0  2021-09-01
149        Tallahassee       0.0  2021-09-01
148             Topeka       0.0  2021-09-01
179         Alexandria       0.0  2021-09-01
178              ERCOT       0.0  2021-09-01
177           Richmond       0.0  2021-09-01
176              Tyler       0.0  2021-09-01
175            Ardmore       0.0  2021-09-01
174             Conroe       0.0  2021-09-01
173             Eugene       0.0  2021-09-01
172          Worcester       0.0  2021-09-01
171           Monahans       0.0  2021-09-01
170     Wallops Island       0.0  2021-09-01
169    College Station       0.0  2021-09-01
168            Lansing       0.0  2021-09-01
167            Cotulla       0.0  2021-09-01
166         Laredo AFB       0.0  2021-09-01
165              CAISO       0.0  2021-09-01
164             Fresno       0.0  2021-09-01
195         Farmington       0.0  2021-09-01
194     Ft. Lauderdale       0.0  2021-09-01
193            Phoenix       0.0  2021-09-01
192            Augusta       0.0  2021-09-01
191            Medford       0.0  2021-09-01
190            Oakland       0.0  2021-09-01
189       Akron-Canton       0.0  2021-09-01
188         Morgantown       0.0  2021-09-01
187            Seattle       0.0  2021-09-01
186    West Palm Beach       0.0  2021-09-01
185            Norfolk       0.0  2021-09-01
184            Wichita       0.0  2021-09-01
231             Tucson       0.0  2021-09-01
230      Klamath Falls       0.0  2021-09-01
229         Huntington       0.0  2021-09-01
4            St. Louis       0.0  2021-09-01
35              Duluth       0.0  2021-09-01
34           SOUTHEAST       0.0  2021-09-01
33                Erie       0.0  2021-09-01
32            Columbus       0.0  2021-09-01
31         Springfield       0.0  2021-09-01
30           Milwaukee       0.0  2021-09-01
29           Allentown       0.0  2021-09-01
27                 JFK       0.0  2021-09-01
26                Gage       0.0  2021-09-01
25             Midland       0.0  2021-09-01
24              Joplin       0.0  2021-09-01
182         Burlington       0.0  2021-09-01
181             Albany       0.0  2021-09-01
180        Baton Rouge       0.0  2021-09-01
211           Beaumont       0.0  2021-09-01
210        Minneapolis       0.0  2021-09-01
209          Covington       0.0  2021-09-01
208         MISO NORTH       0.0  2021-09-01
207      Atlantic City       0.0  2021-09-01
206             Duncan       0.0  2021-09-01
205              Tampa       0.0  2021-09-01
204           Amarillo       0.0  2021-09-01
203              Boise       0.0  2021-09-01
202        Brownsville       0.0  2021-09-01
201            Burbank       0.0  2021-09-01
200          Vancouver       0.0  2021-09-01
199       Poughkeepsie       0.0  2021-09-01
198         Hagerstown       0.0  2021-09-01
197          Cleveland       0.0  2021-09-01
196         San Angelo       0.0  2021-09-01
227         Birmingham       0.0  2021-09-01
226      Chicago Midwy       0.0  2021-09-01
225           Carlsbad       0.0  2021-09-01
224              Tulsa       0.0  2021-09-01
223       Jacksonville       0.0  2021-09-01
222            Abilene       0.0  2021-09-01
221          Rochester       0.0  2021-09-01
220               Wink       0.0  2021-09-01
219          San Diego       0.0  2021-09-01
218      Grand Prairie       0.0  2021-09-01
217          Lexington       0.0  2021-09-01
216             Austin       0.0  2021-09-01
215       North Platte       0.0  2021-09-01
214   Interntnl. Falls       0.0  2021-09-01
213               Waco       0.0  2021-09-01
212         Bridgeport       0.0  2021-09-01
243            Madison       0.0  2021-09-01
258           Scranton       0.0  2021-09-01
257        New Orleans       0.0  2021-09-01
256            Decatur       0.0  2021-09-01
255           Syracuse       0.0  2021-09-01
254           Montreal       0.0  2021-09-01
253           Bismarck       0.0  2021-09-01
252          Pendleton       0.0  2021-09-01
251         Ral-Durham       0.0  2021-09-01
250            Jackson       0.0  2021-09-01
249           Rockford       0.0  2021-09-01
248          Jonesboro       0.0  2021-09-01
7            Kalamazoo       0.0  2021-09-01
6                 Alva       0.0  2021-09-01
5       Los Ang Dwntwn       0.0  2021-09-01
2              Buffalo       0.0  2021-09-01

In [10]:
# checking all unique station names in the table with region as "CAISO"
sql = "SELECT DISTINCT station_name FROM rfo_weather_enriched WHERE region = 'NWPP'"
unique_datatypes = wr.athena.read_sql_query(
    sql=sql,
    database="rfo_analytics",
    boto3_session=session
)
print(unique_datatypes['station_name'].value_counts())

station_name
Tacoma            1
Boise             1
Eugene            1
Portland          1
NWPP              1
Vancouver         1
Yakima            1
Pendleton         1
Billings          1
Medford           1
Reno              1
Salt Lake City    1
Great Falls       1
Klamath Falls     1
Spokane           1
Seattle           1
Name: count, dtype: Int64

In [4]:
conditions='''WHERE region = 'NWPP'
  AND CAST(datetime AS DATE) BETWEEN DATE '2021-09-01' AND DATE '2025-12-31' '''

In [5]:
#To query all columns
# table_info = wr.catalog.table(
#     database="rfo_analytics", 
#     table=table, 
#     boto3_session=session
# )
# columns = table_info['Column Name'].values

#If you know which columns to query
columns = ["datetime","datatype","avgvalue","siteid","station_name","timezone"] # for weather
# columns = ["datetime","avgvalue","objectid","name","yes_objectid","iso"]
# Build SELECT clause with automatic datetime casting
select_parts = []
for col_name in columns:
    if col_name.lower() == 'datetime':
        select_parts.append(f"CAST({col_name} AS timestamp) as {col_name}")
    else:
        select_parts.append(col_name)

select_clause = ",\n    ".join(select_parts)

# Build and execute query
sql = f"""SELECT 
    {select_clause}
FROM {table}
{conditions}
"""

df = wr.athena.read_sql_query(
    sql=sql,
    database="rfo_analytics",
    boto3_session=session
)

In [6]:
#each unique station_name has a unique timezone. construct a dictionary with station_name as key and timezone as value
timezone_dict = df[['station_name','timezone']].drop_duplicates().set_index('station_name').to_dict()['timezone']

In [16]:
#save timezone_dict
import joblib
joblib.dump(timezone_dict, '../data/timezone_dict.pkl')

['../data/timezone_dict.pkl']

In [ ]:
from datetime import datetime
import sys
import os
sys.path.append(os.path.abspath(".."))
from helpers import utc_to_local
import pytz
# Example of converting UTC to a specific timezone


# You can test it with timezone_dict values
# For example:
test_time = datetime.now(pytz.UTC)
local_time = utc_to_local(test_time, timezone_dict['Vancouver'])

In [ ]:
#df's datatype column has two values: 'temperature' and 'temperature_avg', and the corresponding value is in avgvalue column. I want two separate columns 'temperature' and 'temperature_avg' with their values taken from avgvalue column.
df = df[['station_name','datetime','datatype','avgvalue']].pivot(index=['station_name','datetime'], columns='datatype', values='avgvalue').reset_index()
df = df.rename_axis(None, axis=1)  # remove the axis name

In [8]:
df['datetime'].max()

Timestamp('2025-09-22 11:00:00')

In [10]:
#save df a csv file
df.to_csv("../data/ALLWeath_regNWPP_2021-2025.csv", index=False)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1359168 entries, 0 to 1359167
Data columns (total 24 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   datetime          1359168 non-null  datetime64[ns]
 1   siteid            1359168 non-null  string
 2   station_name      1359168 non-null  string
 3   region            1359168 non-null  string
 4   timezone          1274220 non-null  string
 5   cloudCover        1359168 non-null  float64
 6   dewpoint          1359168 non-null  float64
 7   electric_cdd      56208 non-null    float64
 8   electric_hdd      56208 non-null    float64
 9   gas_cdd           56208 non-null    float64
 10  gas_hdd           56208 non-null    float64
 11  heatIndex         1359168 non-null  float64
 12  population_cdd    56208 non-null    float64
 13  population_hdd    56208 non-null    float64
 14  relativeHumidity  1359168 non-null  float64
 15  temperature       1359152 non-null  float64
 16  temperature_avg   56624 non-null    float64
 17  temperature_max   56624 non-null    float64
 18  temperature_min   56624 non-null    float64
 19  weighted_cdd      56624 non-null    float64
 20  weighted_hdd      56624 non-null    float64
 21  windChill         1359168 non-null  float64
 22  windDirection     1359168 non-null  float64
 23  windSpeed         1359168 non-null  float64
dtypes: datetime64[ns](1), float64(19), string(4)
memory usage: 248.9 MB